# -*- coding: utf-8 -*-
"""Data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BI-eL75e84fF7tqRI-XEV813-PI833yN
"""

import pandas as pd
import seaborn as sns
df=pd.read_csv('/Titanic-Dataset.csv')
print(df.head(10))

sns.heatmap(df.isnull())

print(df.duplicated().sum())

print(df.describe())

# 1. Sirf Numerical Data (int aur float) alag karein
num_df = df.select_dtypes(include=['int64', 'float64'])

# 2. Sirf Categorical Data (object/text) alag karein
cat_df = df.select_dtypes(include=['object'])

# Check karne ke liye
print("Numerical Columns:", num_df.columns.tolist())
print("Categorical Columns:", cat_df.columns.tolist())

import matplotlib.pyplot as plt

# Comparison bar chart
data_types = ['Numerical', 'Categorical']
counts = [len(num_df.columns), len(cat_df.columns)]

plt.bar(data_types, counts, color=['blue', 'orange'])
plt.title('Count of Column Types')
plt.show()

# Task: Sab kuch ek saath
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

# Unwanted columns hatana
df.drop(['Name', 'Ticket', 'PassengerId'], axis=1, inplace=True)

print(df.head())

df['Age'] = df['Age'].fillna(df['Age'].median())
df.head(20)

df.drop(columns=['Cabin'], inplace=True)
df.head()

df['SibSp'].unique()

#IQR = Interquartile Range
#Yahi outlier hai — jo baaki data se bahut alag ho.
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(lower, upper)

outliers = df[(df['Age'] < 2.5) | (df['Age'] > 54.5)]
print(outliers['Age'])

import seaborn as sns
sns.boxplot(df['Age'])

from scipy import stats
z = stats.zscore(df['Age'])
outliers = df[abs(z) > 3]

